### ISSUE TITLE
Add ability to specify feed's group when creating a new feed

### ISSUE THREAD

**Issue by brentru** [adafruit/Adafruit_IO_Python#104]
As of now, feeds created will be created in the "default" group.

Instead of creating feeds in the default group, change the create_feed call to include a `group` kwarg:
`def create_feed(self, feed, group=None)`

Group formatting: `https://io.adafruit.com/USERNAME/feeds/GROUP.FEED`

Related thread: https://forums.adafruit.com/viewtopic.php?f=56&t=156692

**Comment by Thuzerland** [comment]
Is there any progress?

**Comment by brentru** [comment]
Closing via https://github.com/adafruit/Adafruit_IO_Python/pull/125
