### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by MarcEngrie** [adafruit/Adafruit_IO_Python#113]
Hi, 

i just downloaded/installed Adafruit_IO Python (3.7.5 on Win 10) library to give it a first try on Adafruit IO platform. 

used the example 'data.py', added user and key and ran it. I came across the date issue

Traceback (most recent call last):
  File "data.py", line 39, in <module>
    aio.send_batch_data(temperature.key, data_list)
  File "C:\Python\lib\site-packages\Adafruit_IO\client.py", line 168, in send_batch_data
    self._post(path, {"data": data_dict})
  File "C:\Python\lib\site-packages\Adafruit_IO\client.py", line 127, in _post
    self._handle_error(response)
  File "C:\Python\lib\site-packages\Adafruit_IO\client.py", line 108, in _handle_error
    raise RequestError(response)
Adafruit_IO.errors.RequestError: Adafruit IO request failed: 422 Unprocessable Entity - request failed - Record invalid. Failed to save data to mengrie/feeds/temperature. data created_at may not be in the future

So it say, date is in the future. Given the fact that I live in EU (Belgium) and platform is most likely in US, I can understand this date issue but what should be used to overcome this? UTC time? 
Or is there another way around?

BTW: in the random_data.py there user and key from Brent are still there. :-(

**Comment by brentru** [comment]
> Adafruit_IO.errors.RequestError: Adafruit IO request failed: 422 Unprocessable Entity - request failed - Record invalid. Failed to save data to mengrie/feeds/temperature. data created_at may not be in the future

@MarcEngrie - Please check if your computer's system date-time is set to an accurate date-time.

**Comment by MarcEngrie** [comment]
Hi Brent,
yes my computer has the right time and is sync via ntp with  time.windows.com (see attachment)
![Annotation 2020-05-26 162320](https://user-images.githubusercontent.com/19575705/82912332-440a5180-9f6d-11ea-9385-7bc94ea2850a.jpg)

**Comment by brentru** [comment]
@MarcEngrie  There may be a small amount of drift between your server time and our server time. We allow no drift on `created_at`.

I'm going to create a patch for this issue, but you may want to try changing the data.py example from 
`data_list = [Data(value=50, created_at=today), Data(value=33, created_at=yesterday)]`
to 
`data_list = [Data(value=50), Data(value=33)]`

**Comment by MarcEngrie** [comment]
Just to help you out finding the right solution, I did the following
now = datetime.datetime.utcnow() - timedelta(hours=4)
today = now.isoformat()
print(today)
This will work
now = datetime.datetime.utcnow() - timedelta(hours=3)
today = now.isoformat()
print(today)
This will fail. 
Of course in non-utc timezone (CEST = CET summertime = UTC +2), this works as well 
now = datetime.datetime.now() - timedelta(hours=6)
today = now.isoformat()
print(today)
while (of course) this fails
now = datetime.datetime.now() - timedelta(hours=5)
today = now.isoformat()
print(today)
(so cloudserver is based in East-Canada?)

**Comment by brentru** [comment]
Unable to replicate, closing.
