### ISSUE TITLE
Create a feed on a specific group using python

### ISSUE THREAD

**Issue by razote** [adafruit/Adafruit_IO_Python#118]
Hi,

In the docs*
https://adafruit-io-python-client.readthedocs.io/en/latest/feeds.html

/# Create Feed object with name 'Foo'.
feed = Feed(name='Foo')

/# Send the Feed to IO to create.
/# The returned object will contain all the details about the created feed.
result = aio.create_feed(feed)

This code will create a feed under the default group. It never mentions how to create on a different group. Upon checking the code, it seems it is not yet implemented.

Hopefully it can be implemented soon!
Thank you!

**Comment by brentru** [comment]
Putting the HTTP API reference here for the future (or if someone wants to tackle it).

Creating a feed in a group:

- https://io.adafruit.com/api/docs/#create-feed-in-a-group

Adding a feed to a group:

- https://io.adafruit.com/api/docs/#add-feed-to-group

**Comment by brentru** [comment]
Closing via https://github.com/adafruit/Adafruit_IO_Python/pull/125
