### ISSUE TITLE
io.adafruit.com

### ISSUE THREAD

**Issue by Infyskybelgaum** [adafruit/Adafruit_IO_Python#126]
I am facing this issue please help me here thank you .

Adafruit_IO.errors.RequestError: Adafruit IO request failed: 404 Not Found - not found - that is an invalid URL, please check the API documentation at https://io.adafruit.com/api/docs to make sure your URL is correct

**Comment by brentru** [comment]
Please do not open duplicate issues, I will assist over on https://github.com/adafruit/Adafruit_IO_Python/issues/127
