### ISSUE TITLE
MQTT doesn't reconnect after several hours of running.

### ISSUE THREAD

**Issue by happy786** [adafruit/Adafruit_IO_Python#130]
Hi,
I have been using your library for so many days and it worked well until now. One thing i changed is changing from raspberry pi 3 to raspberry pi 4.

My program is working fine but after running several hours it disconnect mqtt communication with adafruit io platform and never reconnect unless nd until i re-run the script.

[project.txt](https://github.com/adafruit/Adafruit_IO_Python/files/5976580/project.txt)

**Comment by brentru** [comment]
Hi, could you please add an additional comment with the error from your Raspberry Pi?

**Comment by happy786** [comment]
Hii please find the attached error while it disconnected from adafruit io
[log.txt](https://github.com/adafruit/Adafruit_IO_Python/files/5988727/log.txt)

**Comment by happy786** [comment]
If i change  disconnect function with commenting #raiseMQTT error in mqttclient.py script then there is no error and simply printing " disconnected from adafruit io" and never reconnect.

**Comment by happy786** [comment]
> Hi, could you please add an additional comment with the error from your Raspberry Pi?

Hiii do you mind find a solution for me ? It's been so long i have tried multiple way but it's not working.

**Comment by brentru** [comment]
Could you copy and paste `log.txt` into the comment field? I don't feel comfortable opening a file from GitHub. Thanks

**Comment by happy786** [comment]
> Could you copy and paste the contents of `log.txt` into a comment field? I don't feel comfortable opening a file attached here. Thanks

Sure kindly look into the following.

Unexpected disconnection.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/paho/mqtt/client.py", line 3452, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/home/pi/.local/lib/python3.7/site-packages/paho/mqtt/client.py", line 1779, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/home/pi/.local/lib/python3.7/site-packages/paho/mqtt/client.py", line 1201, in loop
    return self.loop_misc()
  File "/home/pi/.local/lib/python3.7/site-packages/paho/mqtt/client.py", line 1628, in loop_misc
    self._check_keepalive()
  File "/home/pi/.local/lib/python3.7/site-packages/paho/mqtt/client.py", line 2430, in _check_keepalive
    self._do_on_disconnect(rc)
  File "/home/pi/.local/lib/python3.7/site-packages/paho/mqtt/client.py", line 3360, in _do_on_disconnect
    self.on_disconnect(self, self._userdata, rc)
  File "/home/pi/.local/lib/python3.7/site-packages/Adafruit_IO/mqtt_client.py", line 101, in _mqtt_disconnect
    raise MQTTError(rc)
Adafruit_IO.errors.MQTTError: Incorrect protocol version

**Comment by happy786** [comment]
Kindly help me i am at the end of the project but stuck in this problem. Need help.

**Comment by brentru** [comment]
You're using the wrong MQTT protocol version. The Adafruit IO MQTT Broker expects that you should be using v3.1.1

**Comment by happy786** [comment]
i am using already mqtt broker latest version but the problem remain same.

**Comment by petcupaula** [comment]
@happy786 Same issue here. Did you find a solution to this in the end?

**Comment by happy786** [comment]
No, I did not.

**Comment by gruvw** [comment]
I have the same issue please help

**Comment by gruvw** [comment]
My code is working fine with MQTT for about 24 hours but after a while I suddenly get this error telling me that I have the wrong protocol version

**Comment by springjools** [comment]
> Could you copy and paste the contents of `log.txt` into a comment field? I don't feel comfortable opening a file attached here. Thanks

Are you afraid of text files hosted on the github domain?
