### ISSUE TITLE
Documentation Update for `Feed Creation`

### ISSUE THREAD

**Issue by Pjurek3** [adafruit/Adafruit_IO_Python#146]
The [documentation on for feed](https://adafruit-io-python-client.readthedocs.io/en/latest/feeds.html#feed-creation) creation only indicates providing the API key to build the Client but not the username.  Both are required inputs and the examples do not work.  

Fix should update examples on this documentation page to include correct `Client` interface.

**Comment by brentru** [comment]
Resolved in https://github.com/adafruit/Adafruit_IO_Python/pull/147
