### ISSUE TITLE
Syntax error when import MQTTClient on Raspian 9 with Python 3.5.3

### ISSUE THREAD

**Issue by jmangum** [adafruit/Adafruit_IO_Python#156]
- Platform/operating system (i.e. Raspberry Pi with Raspbian operating system,
  Windows 32-bit, Windows 64-bit, Mac OSX 64-bit, etc.):    Operating System: Raspbian GNU/Linux 9 (stretch)
                                                                                                    Kernel: Linux 4.19.66-v7+

- Python version (run `python -version` or `python3 -version`):  Python 3.5.3 (default, Apr  5 2021, 09:00:41)
                                                                                                          [GCC 6.3.0 20170516] on linux

- Error message you are receiving, including any Python exception traces:  

>>> from Adafruit_IO import MQTTClient
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.local/lib/python3.5/site-packages/Adafruit_IO/__init__.py", line 21, in <module>
    from .client import Client
  File "/home/pi/.local/lib/python3.5/site-packages/Adafruit_IO/client.py", line 266
    res = self._get(f'feeds/{feed}/details')
                                          ^
SyntaxError: invalid syntax

- List the steps to reproduce the problem below (if possible attach code or commands
  to run): [See python exception above.  Just trying to import MQTTClient.]

**Comment by tyeth** [comment]
Hey @jmangum thanks for reporting this!
Your version of python is pretty old, I am not sure the minimum version but in my head it's probably 3.8 or 3.10. Also stretch is pretty old now too.
You might want to update for security fixes along with feature and performance improvements, then retest.

**Comment by jmangum** [comment]
Thank you @tyeth .  I believe that the instructions say python 3.4+ is required, so I think I am ok with regards python version (unless the README needs to be updated).  Upgrading Raspian would require a rebuild, which I was hoping to avoid.

**Comment by tyeth** [comment]
Ah good spot. Yeah the readme probably wants updating, seems support for f-strings is possible but not supported out the box https://stackoverflow.com/questions/38865348/are-f-strings-supposed-to-work-in-python-3-4#46225926

**Comment by jmangum** [comment]
Thank you @tyeth.  I should really upgrade both Raspian (to Raspberry Pi OS) and python.

**Comment by tyeth** [comment]
> Thank you @tyeth.  I should really upgrade both Raspian (to Raspberry Pi OS) and python.

Just be aware that comes with some of its own problems / changes / gotchas, mainly the preferred use of virtual environments or venv's, but the odd thing still needing system level installation.

Adafruit learn guides exist for such things though, and the forums and discord offer good company for any encountered problems

**Comment by jmangum** [comment]
Thank you @tyeth.  I ultimately decided to upgrade by to Raspberry Pi OS, which elevated me to python 3.11.  Was able to install and (almost) get it working.  I think that this issue can be closed (noting the possible update to the README regarding minimum requirements).
