### ISSUE TITLE
Import error : No module named Adafruit_IO

### ISSUE THREAD

**Issue by bha14ur** [adafruit/Adafruit_IO_Python#85]
i am trying to run python program in raspberrypi3. but it gives following error.
python3 seasonal_2_streetlight_vinz.py
Traceback (most recent call last):
  File "seasonal_2_streetlight_vinz.py", line 4, in <module>
    from Adafruit_IO import MQTTClient
ModuleNotFoundError: No module named 'Adafruit_IO'

i am also install python 3.6 and run this python code but getting same output.
please help me !

**Comment by ladyada** [comment]
https://github.com/adafruit/Adafruit_IO_Python#installation

**Comment by bha14ur** [comment]
ok..it's working!

**Comment by bha14ur** [comment]
Thank you !

**Comment by saria85** [comment]
But the link above is only for python3!
